---
# tasks file for zabbix-agent
- name: Create host group
  local_action:
    module: zabbix_group
    server_url: "http://{{ zabbix_server_ipaddr }}/zabbix"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    state: present
    host_groups:
      - All_hosts

- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: "http://{{ zabbix_server_ipaddr }}/zabbix"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    host_name: "{{ ansible_hostname }}"
    ##visible_name: "{{ zabbix_agent_visiblename }}"
    #visible_name: "{{ ansible_hostname }}"
    host_groups:
      - All_hosts
    link_templates:
      - 001_Tmpl_ALL_Alive_Ping
      - 002_Tmpl_OS_Linux_Resource-CPU
      - 003_Tmpl_OS_Linux_Resource-Memory
      - 004_Tmpl_OS_Linux_Resource-DISK
      - 005_Tmpl_OS_Linux_Log
      - 006_Tmpl_OS_Linux_Process-Common
#      - 009_Tmpl_Demo_Item
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: ""
        port: 10050

- name: ReStart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
